name: sync-labs-to-feishu-skip-existing

on:
  schedule:
    - cron: "0 1/12 * * *"
  workflow_dispatch:

jobs:
  sync:
    if: github.repository_owner == 'labex-labs'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Clone Scripts
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          git clone https://huhuhang:$GH_TOKEN@github.com/labex-labs/scripts /tmp/scripts
      - name: Sync to Feishu
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
        run: |
          pip install requests
          pip install jsonschema
          python /tmp/scripts/sync-labs-to-feishu.py --appid "$APP_ID" --appsecret "$APP_SECRET" --repo $GITHUB_REPOSITORY --schema /tmp/scripts/lab_schema.json --skip true
