name: sync-labs-contributors

on:
  schedule:
    - cron: "0 20 28 * *"
  workflow_dispatch:

jobs:
  SyncLabsContributors:
    if: github.repository_owner == 'labex-labs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install CLI
        run: |
          git clone https://${{ secrets.GH_TOKEN }}@github.com/labex-labs/labex-cli.git /tmp/labex-cli
          cd /tmp/labex-cli
          pip install --editable .
      - name: sync-labs-contributors
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          labex update index-contributors --ghtoken "$GH_TOKEN" --repo $GITHUB_REPOSITORY --path .
      - name: Formatting index.json
        run: |
          npm i -g prettier prettier-plugin-sh
          npx prettier --write "**/index.json"
          git pull origin master
      - name: Git commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated Contributors
          branch: ${{ github.head_ref }}
