name: sync-labs-set-feetype
on:
  schedule:
    - cron: "0 0 1/10 * *"
  workflow_dispatch:

jobs:
  SyncLabsFeeType:
    if: github.repository_owner == 'labex-labs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - uses: actions/setup-python@v4
        with:
          python-version: "3.x"
      - name: Install CLI
        run: |
          git clone https://github.com/labex-labs/labex-cli.git /tmp/labex-cli
          cd /tmp/labex-cli
          pip install --editable .
      - name: set-fee-type
        run: |
          labex idx feetype --path . --type free
      - name: Formatting index.json
        run: |
          npm i -g prettier prettier-plugin-sh
          npx prettier --write "**/index.json"
          git pull
      - name: Git commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Updated FeeType
          branch: ${{ github.head_ref }}
