name: sync-labs-to-feishu-skip-existing

on:
  schedule:
    - cron: "0 1/12 * * *"
  workflow_dispatch:

jobs:
  sync:
    if: github.repository_owner == 'labex-labs'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install CLI
        run: |
          git clone https://${{ secrets.GH_TOKEN }}@github.com/labex-labs/labex-cli.git /tmp/labex-cli
          cd /tmp/labex-cli
          pip install --editable .
      - name: Sync to Feishu
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_SECRET: ${{ secrets.APP_SECRET }}
        run: |
          labex syc feishu lab --appid "$APP_ID" --appsecret "$APP_SECRET" --repo $GITHUB_REPOSITORY --skip true